[package]
name = "blobfs"
version = "0.1.0"
authors = ["The Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
serde = { version = ">=1.0.27", features = ["serde_derive", "rc"] }
serde_json = ">=1.0.9"
serde_with = { version = "1.6.0", features = ["macros"] }
libc = "0.2"
vm-memory = { version = "0.7.0" }

rafs = { path = "../rafs" }
nydus-error = { path = "../error" }
storage = { path = "../storage", features = ["backend-localfs", "backend-oss", "backend-registry"] }

fuse-backend-rs = { git = "https://github.com/cloud-hypervisor/fuse-backend-rs.git", rev = "1367097" }

[features]
virtiofs = [ "fuse-backend-rs/virtiofs", "vm-memory/backend-mmap"]

[dev-dependencies]
nydus-app = { path = "../app" }
