name: release

on:
  push:
    tags:
     - v[0-9]+.[0-9]+.[0-9]+*
  schedule:
    # Run daily sanity check at 22:08 clock UTC
    - cron: "8 22 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  nydus-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: Swatinem/rust-cache@v1
      with:
        target-dir: |
          ./target-fusedev
          ./target-virtiofs
        cache-on-failure: true
        key: ${{ runner.os }}-cargo-${{ matrix.arch }}
    - name: Build nydus-rs
      run: |
        declare -A rust_arch_map=( ["amd64"]="x86_64" ["arm64"]="aarch64")
        arch=${rust_arch_map[${{ matrix.arch }}]}
        cargo install --version 0.2.1 cross
        rustup component add rustfmt clippy
        make -e ARCH=$arch -e CARGO=cross static-release
        sudo mv target-fusedev/$arch-unknown-linux-musl/release/nydusd nydusd-fusedev
        sudo mv target-fusedev/$arch-unknown-linux-musl/release/nydus-cached .
        sudo mv target-fusedev/$arch-unknown-linux-musl/release/nydus-image .
        sudo mv target-fusedev/$arch-unknown-linux-musl/release/nydusctl .
        sudo mv target-virtiofs/$arch-unknown-linux-musl/release/nydusd nydusd-virtiofs
        sudo cp -r misc/configs .
        sudo chown -R $(id -un):$(id -gn) . ~/.cargo/
    - name: store-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nydus-artifacts-linux-${{ matrix.arch }}
        path: |
          nydusd-fusedev
          nydusd-virtiofs
          nydus-cached
          nydus-image
          nydusctl
          configs

  nydus-macos:
    runs-on: macos-11
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: Swatinem/rust-cache@v1
      with:
        target-dir: |
          ./target-fusedev
        cache-on-failure: true
        key: ${{ runner.os }}-cargo-${{ matrix.arch }}
    - name: build
      run: |
        # MacOS bash is too old to support declare -A
        arch=$(test ${{ matrix.arch }} == "amd64" && echo "x86_64" || echo "aarch64")
        rustup component add rustfmt clippy
        rustup target install $arch-apple-darwin
        make -e ARCH=$arch macos-fusedev
        sudo mv target-fusedev/$arch-apple-darwin/release/nydusd nydusd-fusedev
        sudo mv target-fusedev/$arch-apple-darwin/release/nydus-cached .
        sudo mv target-fusedev/$arch-apple-darwin/release/nydus-image .
        sudo mv target-fusedev/$arch-apple-darwin/release/nydusctl .
        sudo cp -r misc/configs .
        sudo chown -R $(id -un):$(id -gn) . ~/.cargo/
    - name: store-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nydus-artifacts-darwin-${{ matrix.arch }}
        path: |
          nydusd-fusedev
          nydusctl
          configs

  contrib-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      DOCKER: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: cache go mod
      uses: actions/cache@v2
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/contrib/nydusify/go.sum', '**/contrib/ctr-remote/go.sum', '**/contrib/docker-nydus-graphdriver/go.sum', '**/contrib/nydus-overlayfs/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - name: build contrib go components
      run: |
        make -e GOARCH=${{ matrix.arch }} all-contrib-static-release
        sudo mv contrib/ctr-remote/bin/ctr-remote .
        sudo mv contrib/docker-nydus-graphdriver/bin/nydus_graphdriver .
        sudo mv contrib/nydusify/cmd/nydusify .
        sudo mv contrib/nydus-overlayfs/bin/nydus-overlayfs .
    - name: store-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nydus-artifacts-linux-${{ matrix.arch }}
        path: |
          ctr-remote
          nydus_graphdriver
          nydusify
          nydus-overlayfs
          containerd-nydus-grpc

  prepare-tarball-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux]
    needs: [nydus-linux, contrib-linux]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nydus-artifacts-${{ matrix.os }}-${{ matrix.arch }}
        path: nydus-static
    - name: prepare release tarball
      run: |
        tag=$(echo $GITHUB_REF | cut -d/ -f3-)
        tarball="nydus-static-$tag-${{ matrix.os }}-${{ matrix.arch }}.tgz"
        chmod +x nydus-static/*
        tar cf - nydus-static | gzip > ${tarball}
        echo "tarball=${tarball}" >> $GITHUB_ENV

        shasum="$tarball.sha256sum"
        sha256sum $tarball > $shasum
        echo "tarball_shasum=${shasum}" >> $GITHUB_ENV
    - name: store-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nydus-release-tarball
        path: |
          ${{ env.tarball }}
          ${{ env.tarball_shasum }}

  # use a seperate job for darwin because github action if: condition cannot handle && properly.
  prepare-tarball-darwin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        os: [darwin]
    needs: [nydus-macos]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nydus-artifacts-${{ matrix.os }}-${{ matrix.arch }}
        path: nydus-static
    - name: prepare release tarball
      run: |
        tag=$(echo $GITHUB_REF | cut -d/ -f3-)
        tarball="nydus-static-$tag-${{ matrix.os }}-${{ matrix.arch }}.tgz"
        chmod +x nydus-static/*
        tar cf - nydus-static | gzip > ${tarball}
        echo "tarball=${tarball}" >> $GITHUB_ENV

        shasum="$tarball.sha256sum"
        sha256sum $tarball > $shasum
        echo "tarball_shasum=${shasum}" >> $GITHUB_ENV
    - name: store-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nydus-release-tarball
        path: |
          ${{ env.tarball }}
          ${{ env.tarball_shasum }}

  create-release:
    runs-on: ubuntu-latest
    needs: [prepare-tarball-linux, prepare-tarball-darwin]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nydus-release-tarball
        path: nydus-tarball
    - name: prepare release env
      run: |
        echo "tarballs<<EOF" >> $GITHUB_ENV
        cnt=0
        for I in $(ls nydus-tarball);do cnt=$((cnt+1)); echo "nydus-tarball/${I}" >> $GITHUB_ENV; done
        echo "EOF" >> $GITHUB_ENV
        tag=$(echo $GITHUB_REF | cut -d/ -f3-)
        echo "tag=${tag}" >> $GITHUB_ENV
        cat $GITHUB_ENV
    - name: push release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        name: "Nydus Image Service ${{ env.tag }}"
        generate_release_notes: true
        files: |
          ${{ env.tarballs }}
